'use strict';

/*
 * report_generate — regenerates the human-readable mirrors from state (plan §6.1):
 *   - office/BOARD.md : kanban mirror incl. the Awaiting Orchestrator written queue
 *   - office/office-live.json : RAW SIGNALS ONLY (active_role, last_event_time,
 *     mood hint, energy hint) — all animation logic lives in the dashboard (§6.3).
 *   - office/dashboard-data.js : single-line `window.VCNP_DATA = {...}` assignment
 *     so templates/dashboard.html + office/dashboard.html work from file:// with
 *     no fetch/CORS (Wall MVP, plan §6.3-6.4).
 */

const fs = require('fs');
const path = require('path');
const store = require('../store');

const DASHBOARD_DATA_FILE = path.join(store.OFFICE_DIR, 'dashboard-data.js');
const RECENT_EVENTS_LIMIT = 25;

/*
 * Time tunables (live-office plan §4.3) — env-overridable, read at CALL time
 * so tests can override per invocation without re-requiring this module.
 * Primary env names follow the Phase-1 contract; the design doc's
 * VCNP_OFFICE_ACTIVE_MIN is honored as an alias for ACTIVE_THRESHOLD_MIN.
 */
const DEFAULT_TUNABLES = Object.freeze({
  ACTIVE_THRESHOLD_MIN: 30,   // active_role cutoff (was hardcoded `ageMin < 30`)
  ENERGY_DECAY_MIN: 100,      // linear decay horizon (was hardcoded `100 - ageMin`)
  SLEEP_AFTER_MIN: 60,        // mood 'sleeping' cutoff
  COFFEE_AFTER_DONE_MIN: 20,  // post-done coffee window
});

function tunables() {
  const num = (v, dflt) => {
    const n = Number.parseFloat(v);
    return Number.isFinite(n) && n >= 0 ? n : dflt;
  };
  return {
    ACTIVE_THRESHOLD_MIN: num(
      process.env.VCNP_ACTIVE_THRESHOLD_MIN ?? process.env.VCNP_OFFICE_ACTIVE_MIN,
      DEFAULT_TUNABLES.ACTIVE_THRESHOLD_MIN
    ),
    ENERGY_DECAY_MIN: num(process.env.VCNP_ENERGY_DECAY_MIN, DEFAULT_TUNABLES.ENERGY_DECAY_MIN),
    SLEEP_AFTER_MIN: num(process.env.VCNP_SLEEP_AFTER_MIN, DEFAULT_TUNABLES.SLEEP_AFTER_MIN),
    COFFEE_AFTER_DONE_MIN: num(process.env.VCNP_COFFEE_AFTER_DONE_MIN, DEFAULT_TUNABLES.COFFEE_AFTER_DONE_MIN),
  };
}

/*
 * Explicit action→mood map (plan §4.3) — replaces the buggy substring regex
 * `/meeting|gate|standup|review/` whose `review` alternative matched inside
 * qa_review_passed and pinned QA to 'meeting' forever.
 * A null value falls through to role defaults; unknown actions fall through too.
 */
const MOOD_BY_ACTION = {
  qa_review_passed: 'working',
  qa_review_rejected: 'frustrated',
  qa_gate_started: 'meeting',
  meeting_started: 'meeting',
  meeting_ended: null,
  task_created: 'thinking',
  task_assigned: 'working',
  message_posted: 'alert',
  message_answered: 'talking',
  phone_call_received: 'phone',
  work_logged: 'working',
};

/*
 * Fallback for unlisted meeting-ish actions (standup_held, emergency_gate, …).
 * The design doc sketches /\b(meeting|gate|standup)\b/i, but '_' is a regex
 * word character, so \b NEVER matches inside snake_case (qa_gate_started).
 * These boundaries treat '_' as a separator while still rejecting innocent
 * substrings like 'investigate' — the original bug class, not repeated.
 */
const MEETING_FALLBACK_RE = /(?:^|[^a-z])(meeting|gate|standup)(?:$|[^a-z])/i;

const ROLES = ['ceo', 'planner', 'orchestrator', 'executor', 'qa', 'security', 'rc', 'librarian', 'devops'];
const COLUMNS = [
  ['todo', 'Todo'],
  ['doing', 'Doing'],
  ['awaiting_orchestrator', 'Awaiting Orchestrator'],
  ['review', 'Review'],
  ['blocked', 'Blocked'],
  ['done', 'Done'],
];

function taskLine(t) {
  const bits = [`**${t.task_id}** ${t.title}`, t.assignee_role || 'unassigned', t.task_class || '?', `${t.progress_percent}%`, `artifacts: ${t.artifacts.length}`];
  if (t.blockers && t.blockers.length) bits.push(`blockers: ${t.blockers.join('; ')}`);
  return `- ${bits.join(' · ')}`;
}

function renderBoard(state) {
  const cols = { todo: [], doing: [], awaiting_orchestrator: [], review: [], blocked: [], done: [] };
  for (const t of state.tasks) {
    (Object.prototype.hasOwnProperty.call(cols, t.status) ? cols[t.status] : cols.todo).push(t);
  }

  // Preserve historical milestone bullets ("- [x] ...") that predate task rows.
  let legacyDone = [];
  try {
    legacyDone = fs.readFileSync(store.BOARD_FILE, 'utf8')
      .split('\n')
      .filter((l) => /^- \[x\]/.test(l.trim()));
  } catch (_) { /* no previous board */ }

  const L = [];
  L.push('# VCNP Office Board', '');
  L.push('> Human-readable kanban mirror of [`office/state.json`](state.json) — derived from the append-only event ledger [`office/events.log.jsonl`](events.log.jsonl), the single source of truth (plan §6). Regenerated by `report_generate`; works even if MCP is offline.', '');
  for (const [key, label] of COLUMNS) {
    L.push(`## ${label}`, '');
    const items = cols[key];
    if (items.length === 0 && !(key === 'done' && legacyDone.length)) L.push('_(empty)_');
    for (const t of items) L.push(taskLine(t));
    if (key === 'done') for (const b of legacyDone) L.push(b);
    L.push('');
  }
  return L.join('\n');
}

/**
 * Mood hints derived deterministically from the latest real ledger event per
 * role (nothing cosmetic — plan §6.3 "Nothing is cosmetic fakery").
 */
function deriveOfficeLive(events) {
  const now = Date.now();
  const roles = {};
  for (const r of ROLES) {
    roles[r] = { role: r, active_role: false, last_event_time: null, mood: 'sleeping', energy_hint: 0 };
  }
  for (const ev of events) {
    const r = ev.actor && Object.prototype.hasOwnProperty.call(roles, ev.actor) ? ev.actor : null;
    if (!r) continue;
    if (!roles[r].last_event_time || Date.parse(ev.ts) > Date.parse(roles[r].last_event_time)) {
      roles[r].last_event_time = ev.ts;
      roles[r]._latest = ev;
    }
  }
  const T = tunables();
  for (const r of Object.values(roles)) {
    const latest = r._latest;
    delete r._latest;
    if (!latest) continue;
    const ageMin = (now - Date.parse(latest.ts)) / 60000;
    r.active_role = ageMin < T.ACTIVE_THRESHOLD_MIN;
    r.energy_hint = Math.max(0, Math.min(100, Math.round(100 - (ageMin * 100) / T.ENERGY_DECAY_MIN)));
    const action = String(latest.action || '');
    if (ageMin >= T.SLEEP_AFTER_MIN) r.mood = 'sleeping';
    else if (MOOD_BY_ACTION[action]) r.mood = MOOD_BY_ACTION[action];
    else if (MEETING_FALLBACK_RE.test(action)) r.mood = 'meeting';
    else if (action === 'task_updated' && latest.status === 'done' && ageMin < T.COFFEE_AFTER_DONE_MIN) r.mood = 'coffee';
    else if (r.role === 'planner' || r.role === 'orchestrator' || r.role === 'ceo') r.mood = 'thinking';
    else r.mood = 'working';
  }
  return {
    schema_version: store.SCHEMA_VERSION,
    generated_ts: new Date().toISOString(),
    note: 'raw signals only — all animation logic lives in the dashboard app (plan §6.3)',
    roles: Object.values(roles),
  };
}

/**
 * Wall MVP data payload (plan §6.3-6.4): ONE line — `window.VCNP_DATA = {...};`
 * A plain <script src> assignment instead of fetch() so the dashboard works
 * when opened directly from file:// (no server, no CORS).
 * `recent_events` feeds the dashboard's last-events list; everything else is
 * raw derived state + raw live signals (no animation logic here, §6.3).
 */
function writeDashboardData(state, live, events) {
  const recent_events = events.slice(-RECENT_EVENTS_LIMIT).map((e) => ({
    ts: e.ts,
    actor: e.actor,
    action: e.action,
    task_id: e.task_id,
  }));
  const payload = {
    state,
    live,
    generated_at: new Date().toISOString(),
    recent_events,
  };
  store.atomicWriteText(DASHBOARD_DATA_FILE, 'window.VCNP_DATA = ' + JSON.stringify(payload) + ';\n');
}

async function generate() {
  const events = store.readEvents();
  const state = store.rebuildState(events);
  const live = deriveOfficeLive(events);

  store.atomicWriteText(store.BOARD_FILE, renderBoard(state));
  store.atomicWriteJson(store.OFFICE_LIVE_FILE, live);
  writeDashboardData(state, live, events);

  const byStatus = {};
  for (const t of state.tasks) byStatus[t.status] = (byStatus[t.status] || 0) + 1;
  return {
    ok: true,
    board_file: 'office/BOARD.md',
    live_file: 'office/office-live.json',
    dashboard_data_file: path.relative(store.WORKSPACE, DASHBOARD_DATA_FILE),
    project: state.project,
    tasks_total: state.tasks.length,
    by_status: byStatus,
    roles_covered: ROLES.length,
  };
}

const defs = [
  {
    name: 'report_generate',
    description:
      'Regenerate office/BOARD.md (kanban columns incl. Awaiting Orchestrator) from rebuilt state and write ' +
      'office/office-live.json (per-role active_role, last_event_time, mood hint: working/thinking/sleeping/coffee/meeting) ' +
      'and office/dashboard-data.js (single-line window.VCNP_DATA assignment for the file:// dashboard).',
    inputSchema: { type: 'object', properties: {} },
    handler: async () => generate(),
    format: (r) =>
      `Report regenerated — BOARD.md (${r.tasks_total} tasks) + office-live.json (${r.roles_covered} roles) + dashboard-data.js. ` +
      `Project "${r.project.name || '?'}" overall progress: ${r.project.overall_progress}%`,
  },
];

module.exports = {
  defs,
  generate,
  deriveOfficeLive,
  renderBoard,
  writeDashboardData,
  DEFAULT_TUNABLES,
  tunables,
  MOOD_BY_ACTION,
  MEETING_FALLBACK_RE,
  ROLES, // single role registry (live-office plan §2 validators consume it)
};
