'use strict';

/*
 * report_generate — regenerates the human-readable mirrors from state (plan §6.1):
 *   - office/BOARD.md : kanban mirror incl. the Awaiting Orchestrator written queue
 *   - office/office-live.json : RAW SIGNALS ONLY (active_role, last_event_time,
 *     mood hint, energy hint) — all animation logic lives in the dashboard (§6.3).
 */

const fs = require('fs');
const store = require('../store');

const ROLES = ['ceo', 'planner', 'orchestrator', 'executor', 'qa', 'security', 'rc', 'librarian', 'devops'];
const COLUMNS = [
  ['todo', 'Todo'],
  ['doing', 'Doing'],
  ['awaiting_orchestrator', 'Awaiting Orchestrator'],
  ['review', 'Review'],
  ['blocked', 'Blocked'],
  ['done', 'Done'],
];

function taskLine(t) {
  const bits = [`**${t.task_id}** ${t.title}`, t.assignee_role || 'unassigned', t.task_class || '?', `${t.progress_percent}%`, `artifacts: ${t.artifacts.length}`];
  if (t.blockers && t.blockers.length) bits.push(`blockers: ${t.blockers.join('; ')}`);
  return `- ${bits.join(' · ')}`;
}

function renderBoard(state) {
  const cols = { todo: [], doing: [], awaiting_orchestrator: [], review: [], blocked: [], done: [] };
  for (const t of state.tasks) {
    (Object.prototype.hasOwnProperty.call(cols, t.status) ? cols[t.status] : cols.todo).push(t);
  }

  // Preserve historical milestone bullets ("- [x] ...") that predate task rows.
  let legacyDone = [];
  try {
    legacyDone = fs.readFileSync(store.BOARD_FILE, 'utf8')
      .split('\n')
      .filter((l) => /^- \[x\]/.test(l.trim()));
  } catch (_) { /* no previous board */ }

  const L = [];
  L.push('# VCNP Office Board', '');
  L.push('> Human-readable kanban mirror of [`office/state.json`](state.json) — derived from the append-only event ledger [`office/events.log.jsonl`](events.log.jsonl), the single source of truth (plan §6). Regenerated by `report_generate`; works even if MCP is offline.', '');
  for (const [key, label] of COLUMNS) {
    L.push(`## ${label}`, '');
    const items = cols[key];
    if (items.length === 0 && !(key === 'done' && legacyDone.length)) L.push('_(empty)_');
    for (const t of items) L.push(taskLine(t));
    if (key === 'done') for (const b of legacyDone) L.push(b);
    L.push('');
  }
  return L.join('\n');
}

/**
 * Mood hints derived deterministically from the latest real ledger event per
 * role (nothing cosmetic — plan §6.3 "Nothing is cosmetic fakery").
 */
function deriveOfficeLive(events) {
  const now = Date.now();
  const roles = {};
  for (const r of ROLES) {
    roles[r] = { role: r, active_role: false, last_event_time: null, mood: 'sleeping', energy_hint: 0 };
  }
  for (const ev of events) {
    const r = ev.actor && Object.prototype.hasOwnProperty.call(roles, ev.actor) ? ev.actor : null;
    if (!r) continue;
    if (!roles[r].last_event_time || Date.parse(ev.ts) > Date.parse(roles[r].last_event_time)) {
      roles[r].last_event_time = ev.ts;
      roles[r]._latest = ev;
    }
  }
  for (const r of Object.values(roles)) {
    const latest = r._latest;
    delete r._latest;
    if (!latest) continue;
    const ageMin = (now - Date.parse(latest.ts)) / 60000;
    r.active_role = ageMin < 30;
    r.energy_hint = Math.max(0, Math.round(100 - ageMin));
    const action = String(latest.action || '');
    if (ageMin >= 60) r.mood = 'sleeping';
    else if (/meeting|gate|standup|review/.test(action)) r.mood = 'meeting';
    else if (action === 'task_updated' && latest.status === 'done' && ageMin < 20) r.mood = 'coffee';
    else if (['planner', 'orchestrator', 'ceo'].includes(r.role)) r.mood = 'thinking';
    else r.mood = 'working';
  }
  return {
    schema_version: store.SCHEMA_VERSION,
    generated_ts: new Date().toISOString(),
    note: 'raw signals only — all animation logic lives in the dashboard app (plan §6.3)',
    roles: Object.values(roles),
  };
}

async function generate() {
  const events = store.readEvents();
  const state = store.rebuildState(events);

  store.atomicWriteText(store.BOARD_FILE, renderBoard(state));
  store.atomicWriteJson(store.OFFICE_LIVE_FILE, deriveOfficeLive(events));

  const byStatus = {};
  for (const t of state.tasks) byStatus[t.status] = (byStatus[t.status] || 0) + 1;
  return {
    ok: true,
    board_file: 'office/BOARD.md',
    live_file: 'office/office-live.json',
    project: state.project,
    tasks_total: state.tasks.length,
    by_status: byStatus,
    roles_covered: ROLES.length,
  };
}

const defs = [
  {
    name: 'report_generate',
    description:
      'Regenerate office/BOARD.md (kanban columns incl. Awaiting Orchestrator) from rebuilt state and write ' +
      'office/office-live.json (per-role active_role, last_event_time, mood hint: working/thinking/sleeping/coffee/meeting).',
    inputSchema: { type: 'object', properties: {} },
    handler: async () => generate(),
    format: (r) =>
      `Report regenerated — BOARD.md (${r.tasks_total} tasks) + office-live.json (${r.roles_covered} roles). ` +
      `Project "${r.project.name || '?'}" overall progress: ${r.project.overall_progress}%`,
  },
];

module.exports = { defs, generate, deriveOfficeLive, renderBoard };
