#Requires -Version 5.1
<#
.SYNOPSIS
  VCNP Vibe-Office one-click installer (Windows PowerShell).

.DESCRIPTION
  Installs the shared "office" scaffold into a TARGET project folder and
  registers the `vcnp-office` MCP server (absolute path to THIS kit's
  mcp/vcnp-office-mcp/src/server.js) in the target's `.mcp.json`.

  Guarantees:
    - Never overwrites existing office/ files (only fills what is missing).
    - Preserves every existing entry in `.mcp.json` (read -> parse -> add -> write).
    - Refuses to touch a `.mcp.json` that is not valid JSON.

.PARAMETER Target
  Target project folder. Default: current directory.

.EXAMPLE
  .\installer\install.ps1 -Target D:\my-project
#>

param(
    [string]$Target = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'

# Make Persian output readable in modern terminals (best effort).
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch { }

function Fail([string]$En, [string]$Fa) {
    Write-Host ''
    Write-Host "ERROR: $En" -ForegroundColor Red
    Write-Host ([char]0x062E + [char]0x0637 + [char]0x0627 + ": $Fa") -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------- locate kit
$KitRoot      = Split-Path -Parent $PSScriptRoot
$ServerJs     = Join-Path $KitRoot 'mcp/vcnp-office-mcp/src/server.js'
$TemplateHtml = Join-Path $KitRoot 'templates/dashboard.html'

if (-not (Test-Path -LiteralPath $ServerJs)) {
    Fail "kit file missing: $ServerJs" "فایل کیت پیدا نشد: $ServerJs"
}
if (-not (Test-Path -LiteralPath $TemplateHtml)) {
    Fail "kit file missing: $TemplateHtml" "فایل کیت پیدا نشد: $TemplateHtml"
}

Write-Host ''
Write-Host '=== VCNP Vibe-Office installer | نصاب وی‌سی‌ان‌پی ===' -ForegroundColor Cyan
Write-Host "kit source : $KitRoot"

# ------------------------------------------------------------- resolve target
if (-not [IO.Path]::IsPathRooted($Target)) {
    $Target = Join-Path (Get-Location).Path $Target
}
$Target = [IO.Path]::GetFullPath($Target)

if (-not (Test-Path -LiteralPath $Target -PathType Container)) {
    Fail "target folder not found: $Target" "پوشهٔ مقصد پیدا نشد: $Target"
}
Write-Host "target     : $Target"

# --------------------------------------------------------- 1) Node.js >= 20
$nodeVersion = ''
try { $nodeVersion = "$(& node --version 2>$null)" } catch { $nodeVersion = '' }
$nodeMajor = 0
if ($nodeVersion -match '^v(\d+)\.') { $nodeMajor = [int]$Matches[1] }

if ($nodeMajor -lt 20) {
    Write-Host ''
    Write-Host 'Node.js version 20 or newer is required, but it was not found on this machine.' -ForegroundColor Yellow
    Write-Host 'Please install Node.js LTS from https://nodejs.org , reopen the terminal, and run this installer again.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host 'برای اجرای این کیت به Node.js نسخهٔ ۲۰ یا جدیدتر نیاز است، اما روی این سیستم پیدا نشد.' -ForegroundColor Yellow
    Write-Host 'لطفاً ابتدا نسخهٔ LTS را از https://nodejs.org نصب کنید، ترمینال را بسته و دوباره باز کنید، سپس نصاب را دوباره اجرا کنید.' -ForegroundColor Yellow
    exit 1
}
Write-Host "[1/4] Node.js $nodeVersion OK"

# ------------------------------------------- 2) office/ scaffold (fill gaps)
$Office = Join-Path $Target 'office'
New-Item -ItemType Directory -Force -Path (Join-Path $Office 'memory-bank') | Out-Null

function Write-IfMissing([string]$Path, [string]$Content) {
    if (Test-Path -LiteralPath $Path) {
        Write-Host "  = kept existing : $Path"
        return
    }
    [IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "  + created       : $Path"
}

Write-Host '[2/4] Creating office/ scaffold (missing files only — nothing is overwritten):'

$stateJson = @'
{
  "schema_version": "1.0",
  "project": {
    "name": "",
    "goal": "",
    "overall_progress": 0
  },
  "tasks": []
}
'@

Write-IfMissing (Join-Path $Office 'state.json') ($stateJson + "`n")

$boardMd = @'
# VCNP Office Board

> Human-readable kanban mirror of [`office/state.json`](state.json) — derived from the append-only event ledger [`office/events.log.jsonl`](events.log.jsonl), the single source of truth (plan §6). Regenerated by `report_generate`; works even if MCP is offline.

## Todo

_(empty)_

## Doing

_(empty)_

## Awaiting Orchestrator

_(empty)_

## Review

_(empty)_

## Blocked

_(empty)_

## Done

_(empty)_
'@

Write-IfMissing (Join-Path $Office 'BOARD.md') ($boardMd + "`n")

# Append-only ledger — SOURCE OF TRUTH. Must start byte-empty (no BOM).
Write-IfMissing (Join-Path $Office 'events.log.jsonl') ''

$mbHeaders = @{
    'activeContext.md'  = '# Active Context — current focus, open questions, next steps (Librarian-owned)'
    'decisionLog.md'    = '# Decision Log — key decisions with rationale and trade-offs (Librarian-owned)'
    'productContext.md' = '# Product Context — high-level project goals, features, and overall architecture (Librarian-owned)'
    'progress.md'       = "# Progress — what works, what's left, status timeline (Librarian-owned)"
}
foreach ($k in $mbHeaders.Keys) {
    Write-IfMissing (Join-Path (Join-Path $Office 'memory-bank') $k) ($mbHeaders[$k] + "`n")
}

# --------------------------------------------------- 3) register MCP server
Write-Host '[3/4] Registering `vcnp-office` MCP server in .mcp.json:'

$McpJson   = Join-Path $Target '.mcp.json'
$serverAbs = ([IO.Path]::GetFullPath($ServerJs)) -replace '\\', '/'

# read -> JSON parse -> add -> write ; aborts on invalid existing JSON (byte-safe for other entries)
# NOTE: single quotes only inside the JS — PowerShell 5.1 mangles double
# quotes when forwarding arguments to native executables.
$mergeScript = @'
const fs = require('fs');
const file = process.argv[1];
const server = process.argv[2];
let cfg = {};
if (fs.existsSync(file)) {
  let raw;
  try { raw = fs.readFileSync(file, 'utf8'); }
  catch (e) { console.error('cannot read .mcp.json: ' + e.message); process.exit(2); }
  try { cfg = JSON.parse(raw); }
  catch (e) { console.error('existing .mcp.json is not valid JSON - aborting to avoid data loss: ' + e.message); process.exit(2); }
}
if (!cfg.mcpServers || typeof cfg.mcpServers !== 'object' || Array.isArray(cfg.mcpServers)) cfg.mcpServers = {};
cfg.mcpServers['vcnp-office'] = { command: 'node', args: [server] };
fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + '\n');
console.log('OK');
'@

& node -e $mergeScript $McpJson $serverAbs
if ($LASTEXITCODE -ne 0) {
    Fail "could not update $McpJson (see message above)" "به‌روزرسانی ‎.mcp.json ممکن نشد (پیام بالا را ببینید)"
}
if (Test-Path -LiteralPath $McpJson) {
    Write-Host "  + merged 'vcnp-office' (absolute server path) into : $McpJson"
}

# ------------------------------------- 4) dashboard fallback + honest notes
Write-Host '[4/4] Dashboard fallback:'
$dashDst = Join-Path $Office 'dashboard.html'
if (Test-Path -LiteralPath $dashDst) {
    Write-Host "  = kept existing : $dashDst"
} else {
    Copy-Item -LiteralPath $TemplateHtml -Destination $dashDst
    Write-Host "  + copied template fallback : $dashDst"
}

Write-Host ''
Write-Host 'NOTE | توجه' -ForegroundColor Yellow
Write-Host 'This MCP server intentionally exposes NO CLI flags, so the installer cannot'
Write-Host 'pre-generate office/dashboard-data.js. Until the CEO runs the MCP tool'
Write-Host '`report_generate` once, the dashboard honestly shows its built-in'
Write-Host '"no data yet" screen instead of fake numbers.'
Write-Host ''
Write-Host 'این سرور عمداً هیچ پرچم خط فرمانی ندارد؛ بنابراین نصاب نمی‌تواند فایل'
Write-Host '‎office/dashboard-data.js را از پیش بسازد. تا زمانی که مدیر کل ابزار'
Write-Host '‎`report_generate` را یک بار اجرا کند، داشبورد پیام صادقانهٔ «داده‌ای نیست» نشان می‌دهد.'
Write-Host ''

Write-Host '=== NEXT STEPS | گام‌های بعدی ===' -ForegroundColor Green
Write-Host '1. Open the target project in VS Code + RooCode.'
Write-Host '2. Switch to the `vcnp-ceo` mode and describe your goal — the CEO plans and dispatches the work.'
Write-Host '3. After the first tasks exist, ask the CEO to run `report_generate`, then open'
Write-Host "   $dashDst"
Write-Host '   in any browser (double-click works — refresh for fresh data).'
Write-Host 'Done. موفق باشید!' -ForegroundColor Green
