#!/usr/bin/env bash
#
# VCNP Vibe-Office one-click installer (Linux / macOS / Git-Bash).
#
# Installs the shared "office" scaffold into a TARGET project folder and
# registers the `vcnp-office` MCP server (absolute path to THIS kit's
# mcp/vcnp-office-mcp/src/server.js) in the target's `.mcp.json`.
#
# Guarantees:
#   - Never overwrites existing office/ files (only fills what is missing).
#   - Preserves every existing entry in `.mcp.json` (read -> parse -> add -> write).
#   - Refuses to touch a `.mcp.json` that is not valid JSON.
#
# Usage: bash installer/install.sh [TARGET_DIR]   (default: current directory)

set -u

KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER_JS="$KIT_ROOT/mcp/vcnp-office-mcp/src/server.js"
TEMPLATE_HTML="$KIT_ROOT/templates/dashboard.html"

fail() { # fail EN FA
  printf '\nERROR: %s\n\xe2\x9c\x98 \xd8\xae\xd8\xb7\xd8\xa7: %s\n' "$1" "$2" >&2
  exit 1
}

[ -f "$SERVER_JS" ] || fail "kit file missing: $SERVER_JS" "فایل کیت پیدا نشد: $SERVER_JS"
[ -f "$TEMPLATE_HTML" ] || fail "kit file missing: $TEMPLATE_HTML" "فایل کیت پیدا نشد: $TEMPLATE_HTML"

echo ''
echo '=== VCNP Vibe-Office installer | نصاب وی‌سی‌ان‌پی ==='
echo "kit source : $KIT_ROOT"

# ------------------------------------------------------------ resolve target
DEFAULT_PWD="$(pwd)"
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) DEFAULT_PWD="$(cygpath -m "$DEFAULT_PWD" 2>/dev/null || printf '%s' "$DEFAULT_PWD")" ;;
esac

TARGET="${1:-$DEFAULT_PWD}"
case "$TARGET" in
  /*|[A-Za-z]:/*|[A-Za-z]:\\*) ;;                      # already absolute
  *) TARGET="$DEFAULT_PWD/$TARGET" ;;
esac

[ -d "$TARGET" ] || fail "target folder not found: $TARGET" "پوشهٔ مقصد پیدا نشد: $TARGET"
echo "target     : $TARGET"

# --------------------------------------------------------- 1) Node.js >= 20
NODE_MAJOR=0
NODE_VERSION=''
if command -v node >/dev/null 2>&1; then
  NODE_VERSION="$(node --version 2>/dev/null || true)"
  NODE_MAJOR="$(node -p 'parseInt(process.versions.node, 10)' 2>/dev/null || echo 0)"
fi

if [ "${NODE_MAJOR:-0}" -lt 20 ]; then
  echo ''
  echo 'Node.js version 20 or newer is required, but it was not found on this machine.'
  echo 'Please install Node.js LTS from https://nodejs.org , reopen the terminal, and run this installer again.'
  echo ''
  echo 'برای اجرای این کیت به Node.js نسخهٔ ۲۰ یا جدیدتر نیاز است، اما روی این سیستم پیدا نشد.'
  echo 'لطفاً ابتدا نسخهٔ LTS را از https://nodejs.org نصب کنید، ترمینال را بسته و دوباره باز کنید، سپس نصاب را دوباره اجرا کنید.'
  exit 1
fi
echo "[1/4] Node.js ${NODE_VERSION:-unknown} OK"

# ------------------------------------------- 2) office/ scaffold (fill gaps)
OFFICE="$TARGET/office"
mkdir -p "$OFFICE/memory-bank"

write_if_missing() { # write_if_missing PATH CONTENT(with trailing newline)
  if [ -e "$1" ]; then
    echo "  = kept existing : $1"
    return 0
  fi
  printf '%s' "$2" > "$1"
  echo "  + created       : $1"
}

echo '[2/4] Creating office/ scaffold (missing files only — nothing is overwritten):'

STATE_JSON='{
  "schema_version": "1.0",
  "project": {
    "name": "",
    "goal": "",
    "overall_progress": 0
  },
  "tasks": []
}
'
write_if_missing "$OFFICE/state.json" "$STATE_JSON"

BOARD_MD='# VCNP Office Board

> Human-readable kanban mirror of [`office/state.json`](state.json) — derived from the append-only event ledger [`office/events.log.jsonl`](events.log.jsonl), the single source of truth (plan §6). Regenerated by `report_generate`; works even if MCP is offline.

## Todo

_(empty)_

## Doing

_(empty)_

## Awaiting Orchestrator

_(empty)_

## Review

_(empty)_

## Blocked

_(empty)_

## Done

_(empty)_
'
write_if_missing "$OFFICE/BOARD.md" "$BOARD_MD"

# Append-only ledger — SOURCE OF TRUTH. Must start byte-empty (no BOM).
write_if_missing "$OFFICE/events.log.jsonl" ''

write_if_missing "$OFFICE/memory-bank/activeContext.md" \
  '# Active Context — current focus, open questions, next steps (Librarian-owned)
'
write_if_missing "$OFFICE/memory-bank/decisionLog.md" \
  '# Decision Log — key decisions with rationale and trade-offs (Librarian-owned)
'
write_if_missing "$OFFICE/memory-bank/productContext.md" \
  '# Product Context — high-level project goals, features, and overall architecture (Librarian-owned)
'
write_if_missing "$OFFICE/memory-bank/progress.md" \
  "# Progress — what works, what's left, status timeline (Librarian-owned)
"

# --------------------------------------------------- 3) register MCP server
echo '[3/4] Registering `vcnp-office` MCP server in .mcp.json:'

MCP_JSON="$TARGET/.mcp.json"
SERVER_ABS="$SERVER_JS"
case "$SERVER_ABS" in
  /*|[A-Za-z]:/*) ;;                    # already absolute
  *) SERVER_ABS="$DEFAULT_PWD/${SERVER_ABS#./}" ;;
esac
SERVER_ABS="${SERVER_ABS//\\//}"        # forward slashes are JSON-friendly

# read -> JSON parse -> add -> write ; aborts on invalid existing JSON (byte-safe for other entries)
MERGE_JS='const fs = require("fs"); const file = process.argv[1]; const server = process.argv[2]; let cfg = {}; if (fs.existsSync(file)) { let raw; try { raw = fs.readFileSync(file, "utf8"); } catch (e) { console.error("cannot read .mcp.json: " + e.message); process.exit(2); } try { cfg = JSON.parse(raw); } catch (e) { console.error("existing .mcp.json is not valid JSON - aborting to avoid data loss: " + e.message); process.exit(2); } } if (!cfg.mcpServers || typeof cfg.mcpServers !== "object" || Array.isArray(cfg.mcpServers)) cfg.mcpServers = {}; cfg.mcpServers["vcnp-office"] = { command: "node", args: [server] }; fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + "\n"); console.log("OK");'

MERGE_OUT="$(node -e "$MERGE_JS" "$MCP_JSON" "$SERVER_ABS" 2>&1)" || \
  fail "could not update $MCP_JSON — $MERGE_OUT" "به‌روزرسانی ‎.mcp.json ممکن نشد — $MERGE_OUT"
echo "  + merged \`vcnp-office\` (absolute server path) into : $MCP_JSON"

# ------------------------------------- 4) dashboard fallback + honest notes
echo '[4/4] Dashboard fallback:'
DASH_DST="$OFFICE/dashboard.html"
if [ -e "$DASH_DST" ]; then
  echo "  = kept existing : $DASH_DST"
else
  cp "$TEMPLATE_HTML" "$DASH_DST"
  echo "  + copied template fallback : $DASH_DST"
fi

echo ''
echo 'NOTE | توجه'
echo 'This MCP server intentionally exposes NO CLI flags, so the installer cannot'
echo 'pre-generate office/dashboard-data.js. Until the CEO runs the MCP tool'
echo '`report_generate` once, the dashboard honestly shows its built-in'
echo '"no data yet" screen instead of fake numbers.'
echo ''
echo 'این سرور عمداً هیچ پرچم خط فرمانی ندارد؛ بنابراین نصاب نمی‌تواند فایل'
echo '‎office/dashboard-data.js را از پیش بسازد. تا زمانی که مدیر کل ابزار'
echo '‎`report_generate` را یک بار اجرا کند، داشبورد پیام صادقانهٔ «داده‌ای نیست» نشان می‌دهد.'
echo ''

echo '=== NEXT STEPS | گام‌های بعدی ==='
echo '1. Open the target project in VS Code + RooCode.'
echo '2. Switch to the `vcnp-ceo` mode and describe your goal — the CEO plans and dispatches the work.'
echo '3. After the first tasks exist, ask the CEO to run `report_generate`, then open'
echo "   $DASH_DST"
echo '   in any browser (double-click works — refresh for fresh data).'
echo 'Done. موفق باشید!'
