#!/usr/bin/env bash
#
# VCNP Vibe-Office one-click installer (Linux / macOS / Git-Bash).
#
# Installs the shared "office" scaffold into a TARGET project folder,
# registers the `vcnp-office` MCP server (absolute path to THIS kit's
# mcp/vcnp-office-mcp/src/server.js, PINNED via VCNP_OFFICE_WORKSPACE so the
# target's own office/ is used even when the kit sits inside/near the
# target) in the target's `.mcp.json`, copies the "brain" files the roles
# need to run standalone (.roomodes.json, core/, skills/, adapters/, the
# Claude Code adapter), then starts the live server and opens the studio
# view — nothing manual left for the end user.
#
# Guarantees:
#   - Never overwrites existing office/ files (only fills what is missing) —
#     that's per-project DATA. The brain files ARE overwritten every run —
#     they are kit CODE and should stay in sync with the kit version.
#   - Preserves every existing entry in `.mcp.json` (read -> parse -> add -> write).
#   - Refuses to touch a `.mcp.json` that is not valid JSON.
#
# Usage: bash installer/install.sh [TARGET_DIR]   (default: current directory)

set -u

KIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER_JS="$KIT_ROOT/mcp/vcnp-office-mcp/src/server.js"
TEMPLATE_HTML="$KIT_ROOT/templates/dashboard.html"

fail() { # fail EN FA
  printf '\nERROR: %s\n\xe2\x9c\x98 \xd8\xae\xd8\xb7\xd8\xa7: %s\n' "$1" "$2" >&2
  exit 1
}

[ -f "$SERVER_JS" ] || fail "kit file missing: $SERVER_JS" "فایل کیت پیدا نشد: $SERVER_JS"
[ -f "$TEMPLATE_HTML" ] || fail "kit file missing: $TEMPLATE_HTML" "فایل کیت پیدا نشد: $TEMPLATE_HTML"

echo ''
echo '=== VCNP Vibe-Office installer | نصاب وی‌سی‌ان‌پی ==='
echo "kit source : $KIT_ROOT"

# ------------------------------------------------------------ resolve target
DEFAULT_PWD="$(pwd)"
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) DEFAULT_PWD="$(cygpath -m "$DEFAULT_PWD" 2>/dev/null || printf '%s' "$DEFAULT_PWD")" ;;
esac

TARGET="${1:-$DEFAULT_PWD}"
case "$TARGET" in
  /*|[A-Za-z]:/*|[A-Za-z]:\\*) ;;                      # already absolute
  *) TARGET="$DEFAULT_PWD/$TARGET" ;;
esac

[ -d "$TARGET" ] || fail "target folder not found: $TARGET" "پوشهٔ مقصد پیدا نشد: $TARGET"
echo "target     : $TARGET"

# --------------------------------------------------------- 1) Node.js >= 20
NODE_MAJOR=0
NODE_VERSION=''
if command -v node >/dev/null 2>&1; then
  NODE_VERSION="$(node --version 2>/dev/null || true)"
  NODE_MAJOR="$(node -p 'parseInt(process.versions.node, 10)' 2>/dev/null || echo 0)"
fi

if [ "${NODE_MAJOR:-0}" -lt 20 ]; then
  echo ''
  echo 'Node.js version 20 or newer is required, but it was not found on this machine.'
  echo 'Please install Node.js LTS from https://nodejs.org , reopen the terminal, and run this installer again.'
  echo ''
  echo 'برای اجرای این کیت به Node.js نسخهٔ ۲۰ یا جدیدتر نیاز است، اما روی این سیستم پیدا نشد.'
  echo 'لطفاً ابتدا نسخهٔ LTS را از https://nodejs.org نصب کنید، ترمینال را بسته و دوباره باز کنید، سپس نصاب را دوباره اجرا کنید.'
  exit 1
fi
echo "[1/6] Node.js ${NODE_VERSION:-unknown} OK"

# ------------------------------------------- 2) office/ scaffold (fill gaps)
OFFICE="$TARGET/office"
mkdir -p "$OFFICE/memory-bank"

write_if_missing() { # write_if_missing PATH CONTENT(with trailing newline)
  if [ -e "$1" ]; then
    echo "  = kept existing : $1"
    return 0
  fi
  printf '%s' "$2" > "$1"
  echo "  + created       : $1"
}

echo '[2/6] Creating office/ scaffold (missing files only — nothing is overwritten):'

STATE_JSON='{
  "schema_version": "1.0",
  "project": {
    "name": "",
    "goal": "",
    "overall_progress": 0
  },
  "tasks": []
}
'
write_if_missing "$OFFICE/state.json" "$STATE_JSON"

BOARD_MD='# VCNP Office Board

> Human-readable kanban mirror of [`office/state.json`](state.json) — derived from the append-only event ledger [`office/events.log.jsonl`](events.log.jsonl), the single source of truth (plan §6). Regenerated by `report_generate`; works even if MCP is offline.

## Todo

_(empty)_

## Doing

_(empty)_

## Awaiting Orchestrator

_(empty)_

## Review

_(empty)_

## Blocked

_(empty)_

## Done

_(empty)_
'
write_if_missing "$OFFICE/BOARD.md" "$BOARD_MD"

# Append-only ledger — SOURCE OF TRUTH. Must start byte-empty (no BOM).
write_if_missing "$OFFICE/events.log.jsonl" ''

write_if_missing "$OFFICE/memory-bank/activeContext.md" \
  '# Active Context — current focus, open questions, next steps (Librarian-owned)
'
write_if_missing "$OFFICE/memory-bank/decisionLog.md" \
  '# Decision Log — key decisions with rationale and trade-offs (Librarian-owned)
'
write_if_missing "$OFFICE/memory-bank/productContext.md" \
  '# Product Context — high-level project goals, features, and overall architecture (Librarian-owned)
'
write_if_missing "$OFFICE/memory-bank/progress.md" \
  "# Progress — what works, what's left, status timeline (Librarian-owned)
"

# --------------------------------------------------- 3) copy the "brain"
# Kit CODE, not project data — always overwritten so the target stays in
# sync with the kit version you're installing from.
echo '[3/6] Copying role definitions (RooCode modes, charters, skills, Claude Code adapter):'

copy_kit_dir() { # copy_kit_dir REL_PATH
  local rel="$1" src="$KIT_ROOT/$1"
  [ -e "$src" ] || return 0
  mkdir -p "$TARGET/$(dirname "$rel")"
  cp -R "$src" "$TARGET/$rel"
  echo "  + synced        : $rel"
}

for f in .roomodes.json .roomodes; do
  [ -e "$KIT_ROOT/$f" ] && cp "$KIT_ROOT/$f" "$TARGET/$f" && echo "  + synced        : $f"
done
copy_kit_dir core
copy_kit_dir skills
copy_kit_dir adapters
copy_kit_dir .claude/agents/vcnp
copy_kit_dir .claude/commands/vcnp

# Claude Code only auto-discovers skills under .claude/skills/, not the
# root skills/ folder Roo reads — mirror the 7 VCNP skills there too, with
# their core/ links bumped one level deeper (real gap found in testing).
for s in core-board-ops core-constitution core-protocol deploy-server security-basics smart-resources web-design; do
  src="$KIT_ROOT/skills/$s"
  [ -e "$src" ] || continue
  dst="$TARGET/.claude/skills/$s"
  mkdir -p "$(dirname "$dst")"
  cp -R "$src" "$dst"
  if [ -f "$dst/SKILL.md" ]; then
    sed -i.bak 's#\.\./\.\./core#../../../core#g' "$dst/SKILL.md" && rm -f "$dst/SKILL.md.bak"
  fi
  echo "  + synced        : .claude/skills/$s"
done
if [ -e "$KIT_ROOT/.claude/commands/office.md" ]; then
  mkdir -p "$TARGET/.claude/commands"
  cp "$KIT_ROOT/.claude/commands/office.md" "$TARGET/.claude/commands/office.md"
  echo '  + synced        : .claude/commands/office.md'
fi

# --------------------------------------------------- 4) register MCP server
echo '[4/6] Registering `vcnp-office` MCP server in .mcp.json:'

MCP_JSON="$TARGET/.mcp.json"
SERVER_ABS="$SERVER_JS"
case "$SERVER_ABS" in
  /*|[A-Za-z]:/*) ;;                    # already absolute
  *) SERVER_ABS="$DEFAULT_PWD/${SERVER_ABS#./}" ;;
esac
SERVER_ABS="${SERVER_ABS//\\//}"        # forward slashes are JSON-friendly
TARGET_ABS="${TARGET//\\//}"

# read -> JSON parse -> add -> write ; aborts on invalid existing JSON (byte-safe for other entries)
# VCNP_OFFICE_WORKSPACE is PINNED (fixes a real bug found in testing): the
# server's directory-walk-then-cwd fallback can silently resolve to the
# KIT's own office/ instead of the target's when the kit sits inside/near
# the target — a very normal layout.
MERGE_JS='const fs = require("fs"); const file = process.argv[1]; const server = process.argv[2]; const workspace = process.argv[3]; let cfg = {}; if (fs.existsSync(file)) { let raw; try { raw = fs.readFileSync(file, "utf8"); } catch (e) { console.error("cannot read .mcp.json: " + e.message); process.exit(2); } try { cfg = JSON.parse(raw); } catch (e) { console.error("existing .mcp.json is not valid JSON - aborting to avoid data loss: " + e.message); process.exit(2); } } if (!cfg.mcpServers || typeof cfg.mcpServers !== "object" || Array.isArray(cfg.mcpServers)) cfg.mcpServers = {}; cfg.mcpServers["vcnp-office"] = { command: "node", args: [server], env: { VCNP_OFFICE_WORKSPACE: workspace } }; fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + "\n"); console.log("OK");'

MERGE_OUT="$(node -e "$MERGE_JS" "$MCP_JSON" "$SERVER_ABS" "$TARGET_ABS" 2>&1)" || \
  fail "could not update $MCP_JSON — $MERGE_OUT" "به‌روزرسانی ‎.mcp.json ممکن نشد — $MERGE_OUT"
echo "  + merged \`vcnp-office\` (absolute server path, pinned workspace) into : $MCP_JSON"

# ------------------------------------------------- 5) dashboard fallback
echo '[5/6] Dashboard fallback:'
DASH_DST="$OFFICE/dashboard.html"
if [ -e "$DASH_DST" ]; then
  echo "  = kept existing : $DASH_DST"
else
  cp "$TEMPLATE_HTML" "$DASH_DST"
  echo "  + copied template fallback : $DASH_DST"
fi

# --------------------- 6) start the live server + open the studio view now
# The user should not have to do ANYTHING manual after this script.
echo '[6/6] Starting the live office server and opening the studio view:'
PORT=7788
export VCNP_OFFICE_WORKSPACE="$TARGET_ABS"
export VCNP_OFFICE_PORT="$PORT"
LIVE_SERVER_JS="$KIT_ROOT/mcp/vcnp-office-mcp/src/live-server.js"

health_ok() { curl -fsS "http://127.0.0.1:$PORT/healthz" 2>/dev/null | grep -q '"ok":true'; }

if health_ok; then
  echo "  = already running on 127.0.0.1:$PORT — not starting a second instance"
else
  nohup node "$LIVE_SERVER_JS" >/dev/null 2>&1 &
  disown 2>/dev/null || true
  tries=0
  until health_ok || [ "$tries" -ge 20 ]; do sleep 0.5; tries=$((tries + 1)); done
  if health_ok; then
    echo "  + live server started and healthy on 127.0.0.1:$PORT"
  else
    echo '  ! live server did not report healthy in time — start it manually with `npm run live` in mcp/vcnp-office-mcp'
  fi
fi

STUDIO_URL="http://127.0.0.1:$PORT/live/studio.html"
if health_ok; then
  OPENER=''
  case "$(uname -s)" in
    Darwin) OPENER='open' ;;
    MINGW*|MSYS*|CYGWIN*) OPENER='cmd //c start ""' ;;
    *) command -v xdg-open >/dev/null 2>&1 && OPENER='xdg-open' ;;
  esac
  if [ -n "$OPENER" ]; then
    eval "$OPENER \"$STUDIO_URL\"" >/dev/null 2>&1 && echo "  + opened in your default browser : $STUDIO_URL" \
      || echo "  ! could not auto-open a browser — open this URL yourself: $STUDIO_URL"
  else
    echo "  ! no known browser-opener on this system — open this URL yourself: $STUDIO_URL"
  fi
fi

echo ''
echo '=== NEXT STEPS | گام‌های بعدی ==='
echo "1. The live office is already open at $STUDIO_URL — nothing else to run."
echo '2. Talk to any role: in Claude Code Desktop type `/vcnp:ceo` (or any `/vcnp:<role>`),'
echo '   or in VS Code + RooCode switch to the `vcnp-ceo` mode. Describe your goal in plain'
echo '   language — it appears live in the browser within seconds.'
echo '3. Later, reopen the live office anytime with the `/office` command (Claude Code) —'
echo '   it reuses the already-running server instead of starting a second one.'
echo 'Done. موفق باشید!'
